In [5]:
from sklearn.cluster import KMeans
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import fsolve

### This code will produce arbitrary samples of binary deep eutectic solvents, taking the minimum and maximum mole fractions of each component, number of samples desired to make, and number of trials for the k-means clustering (should be much greater than the number of samples desired to produce). This can easily be modified for ternary deep eutectic solvents. 

In [34]:
def Binary_DES_Generator(min_QAS, min_HBD, max_QAS, max_HBD, samples, trials):
    
    #The minimum mole fractions of each component.
    lower_bounds = np.array([min_QAS, min_HBD])
    
    #The maximum mole fractions of each component. 
    upper_bounds = np.array([max_QAS, max_HBD])

    #Generating random DES compositions within the design contraints, mole fractions of each composition must = 1. 
    DES_trials = np.random.rand(trials*20,2)
    DES_trials = DES_trials*(upper_bounds-lower_bounds)+lower_bounds

    #Adding mole fractions of each component in the random trial. 
    mole_sum = np.sum(DES_trials, axis=1)
    
    #Divide each component by the sum of all components to obtain compositions whose mole fractions =1. 
    DES_samples = DES_trials/mole_sum[:,None]
    
    #This normalization may still lead to compositions that do not satisfy the constraint 
    
    #isolating compositions that do not meet upper bound contraints
    upper_check = DES_samples>upper_bounds
    
    #isolating compositions that do not meet upper bound contraints
    lower_check = DES_samples<lower_bounds
    
    #Combine all checks, compositions not meeting constraints will be removed
    combined_check = np.append(upper_check, lower_check, axis=1)

    #compositions that have no violations are added to SafeList 
    SafeList = np.any(combined_check, axis=1)

    #compositions violating constraints are added to DeleteList
    DeleteList = ~SafeList

    
    Feasible_DES_samples = DES_samples[DeleteList,:]
    print(" "+str(len(Feasible_DES_samples))+" feasible DES samples generated, clustered into "+str(samples)+" samples")

    #Apply K-means clustering to DES samples
    #Number of Clusters = Final desired samples
    kmeans = KMeans(n_clusters=samples, random_state=0).fit(Feasible_DES_samples)
    
    
    DES_Centroids = kmeans.cluster_centers_

    return(DES_Centroids)



## Generalized

In [4]:
def Gen_Binary_DES_Generator(min_comps, max_comps, samples, trials):
    
    #The minimum mole fractions of each component.
    lower_bounds = np.array(min_comps)
    
    #The maximum mole fractions of each component. 
    upper_bounds = np.array(max_comps)

    #Generating random DES compositions within the design contraints, mole fractions of each composition must = 1. 
    DES_trials = np.random.rand(trials*20,2)
    DES_trials = DES_trials*(upper_bounds-lower_bounds)+lower_bounds

    #Adding mole fractions of each component in the random trial. 
    mole_sum = np.sum(DES_trials, axis=1)
    
    #Divide each component by the sum of all components to obtain compositions whose mole fractions =1. 
    DES_samples = DES_trials/mole_sum[:,None]
    
    #This normalization may still lead to compositions that do not satisfy the constraint 
    
    #isolating compositions that do not meet upper bound contraints
    upper_check = DES_samples>upper_bounds
    
    #isolating compositions that do not meet upper bound contraints
    lower_check = DES_samples<lower_bounds
    
    #Combine all checks, compositions not meeting constraints will be removed
    combined_check = np.append(upper_check, lower_check, axis=1)

    #compositions that have no violations are added to SafeList 
    SafeList = np.any(combined_check, axis=1)

    #compositions violating constraints are added to DeleteList
    DeleteList = ~SafeList

    
    Feasible_DES_samples = DES_samples[DeleteList,:]
    print(" "+str(len(Feasible_DES_samples))+" feasible DES samples generated, clustered into "+str(samples)+" samples")

    #Apply K-means clustering to DES samples
    #Number of Clusters = Final desired samples
    kmeans = KMeans(n_clusters=samples, random_state=0).fit(Feasible_DES_samples)
    
    
    DES_Centroids = kmeans.cluster_centers_

    return(DES_Centroids)

### Generate binary DES with lower mole fractions of 0.2, 0.3 (QAS, HBD) and upper mole fractions of 0.7, 0.8 (QAS, HBD). Produce 96 samples with 192 trials for the clustering.

In [15]:
DES_molfrac= Binary_DES_Generator(0.2, 0.3, 0.7, 0.8, 96, 192)

 3840 feasible DES samples generated, clustered into 96 samples


### May also save the output as a variable. Note you will get different mole fractions each time so be sure to keep track if you need them.

In [6]:
A = Binary_DES_Generator(0.3, 0.3, 0.7, 0.8, 96, 192)
# A 

 3798 feasible DES samples generated, clustered into 96 samples


### The next function will combine the previous function with code to convert mole fractions to a list of lists of volumes that can be directly inputed into code for sample preparation in a pipetting robot (OT-2).

In [7]:
def convert_mole_fractions_to_volumes(stock_QAS, stock_HBD, min_QAS, min_HBD, max_QAS, max_HBD, samples, trials):
    QAS = [] # empty list to append calculated volumes in microL
    HBD = []
    DES_mole_fractions = Binary_DES_Generator(min_QAS, min_HBD, max_QAS, max_HBD, samples, trials)
    for row in DES_mole_fractions: 
        def f(x) :
            y = np.zeros(np.size(x))                                                                           
            y[0] = x[0] + x[1] - 125  #input desired volume                                                                   
            y[1] = ((stock_QAS*x[0])/((stock_QAS*x[0]) + (stock_HBD*x[1]))) - row[0]
            y[2] = ((stock_HBD*x[1])/((stock_QAS*x[0]) + (stock_HBD*x[1]))) - row[1]
            return y
        x0 = np.array([100.0, 100.0, 100.0])  
        x = fsolve(f, x0)
        QAS.append(x[0])
        HBD.append(x[1])
        volumes = [QAS,HBD]

    return(volumes)

In [39]:
    DES_molfrac = Binary_DES_Generator(.2, .2, .8, .8, 96, 10)


 200 feasible DES samples generated, clustered into 96 samples


## Generalized conversion to volumes

In [41]:
len(DES_molfrac)
print(DES_molfrac)

[[0.75065191 0.24934809]
 [0.36791297 0.63208703]
 [0.52417857 0.47582143]
 [0.62567579 0.37432421]
 [0.44108315 0.55891685]
 [0.29988323 0.70011677]
 [0.69269626 0.30730374]
 [0.56731269 0.43268731]
 [0.4715866  0.5284134 ]
 [0.2518089  0.7481911 ]
 [0.40776108 0.59223892]
 [0.33196621 0.66803379]
 [0.58673917 0.41326083]
 [0.65428542 0.34571458]
 [0.4906495  0.5093505 ]
 [0.5456631  0.4543369 ]
 [0.4549097  0.5450903 ]
 [0.42310675 0.57689325]
 [0.77322352 0.22677648]
 [0.37339667 0.62660333]
 [0.66747494 0.33252506]
 [0.72295726 0.27704274]
 [0.50518316 0.49481684]
 [0.35010784 0.64989216]
 [0.26926333 0.73073667]
 [0.60743414 0.39256586]
 [0.38680342 0.61319658]
 [0.28430705 0.71569295]
 [0.31243416 0.68756584]
 [0.68304991 0.31695009]
 [0.56062208 0.43937792]
 [0.59421955 0.40578045]
 [0.58030786 0.41969214]
 [0.35914616 0.64085384]
 [0.70665682 0.29334318]
 [0.54272137 0.45727863]
 [0.39729839 0.60270161]
 [0.64542232 0.35457768]
 [0.55354232 0.44645768]
 [0.76563261 0.23436739]


In [3]:
list =[0] * 96
print(list)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [11]:
array = np.zeros((8,12))
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
len(array[0])

12

In [43]:
DES_molfrac[0]

array([0.75065191, 0.24934809])

In [51]:
all_samples = []
for i in range(96):
    all_samples.append(i)
    
print(all_samples)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]


In [70]:
index=0
array = np.zeros((8,12))


for i in range(len(array[0])):
    for j in range(len(array)):
        array[j, i] = comp1[index] 
        index = index +1
        
print(array)

[[0.75065191 0.4715866  0.4549097  0.26926333 0.58030786 0.43346565
  0.69924989 0.34177252 0.43780666 0.72786539 0.69548312 0.47457658]
 [0.36791297 0.2518089  0.42310675 0.60743414 0.35914616 0.24707624
  0.47774177 0.4184449  0.56962899 0.48799756 0.36558089 0.69724009]
 [0.52417857 0.40776108 0.77322352 0.38680342 0.70665682 0.51767419
  0.37709106 0.75610999 0.31744966 0.67863331 0.54098182 0.44384152]
 [0.62567579 0.33196621 0.37339667 0.28430705 0.54272137 0.44766386
  0.67316677 0.48316346 0.45779757 0.50055108 0.52093251 0.3563218 ]
 [0.44108315 0.58673917 0.66747494 0.31243416 0.39729839 0.32508585
  0.65102814 0.66254257 0.24273251 0.38177801 0.60382883 0.57699194]
 [0.29988323 0.65428542 0.72295726 0.68304991 0.64542232 0.53587261
  0.46028855 0.29265404 0.46745586 0.45318551 0.3344495  0.68555239]
 [0.69269626 0.4906495  0.50518316 0.56062208 0.55354232 0.49671749
  0.4119625  0.42739765 0.30805012 0.62257365 0.57211827 0.55597628]
 [0.56731269 0.5456631  0.35010784 0.5942

In [71]:
ordered = []
for i in range(len(array)):
    hold = array[i]
    #print(hold)
    ordered.extend(hold)

print(ordered)

[0.7506519120055682, 0.4715865983322038, 0.45490970261466435, 0.269263325124163, 0.580307858760063, 0.43346564725017395, 0.6992498852671155, 0.341772524260123, 0.4378066600473607, 0.7278653876459271, 0.6954831237299075, 0.47457658022310223, 0.36791296887462466, 0.2518088988460535, 0.42310674599295583, 0.6074341383970799, 0.3591461618766185, 0.24707624461173144, 0.4777417707230687, 0.4184449015825262, 0.5696289898734429, 0.4879975649618306, 0.36558088561319324, 0.697240091045177, 0.5241785694462062, 0.40776107805949874, 0.7732235181128915, 0.38680342384254485, 0.7066568169931434, 0.5176741861695549, 0.3770910560797914, 0.7561099901269652, 0.31744965818488924, 0.6786333106304895, 0.5409818207512473, 0.4438415153317072, 0.6256757894811007, 0.33196621078815547, 0.3733966742705455, 0.2843070466360036, 0.5427213653788738, 0.4476638551171744, 0.6731667747016513, 0.4831634620345979, 0.45779756887912615, 0.5005510759258127, 0.5209325052498803, 0.3563217950106742, 0.4410831515325249, 0.586739174

In [54]:
len(DES_molfrac)

96

In [62]:
number = len(DES_molfrac[0])
comp1 = []
comp2 = []


for i in range(number):
    if i == 0:
        for row in DES_molfrac:
            hold = row[i]
            comp1.append(hold)
    elif i == 1:
        for row in DES_molfrac:
            hold = row[i]
            comp2.append(hold)       
    else:
        pass
        


In [63]:
print(comp1)

[0.7506519120055682, 0.36791296887462466, 0.5241785694462062, 0.6256757894811007, 0.4410831515325249, 0.2998832270640001, 0.6926962564928324, 0.5673126945507219, 0.4715865983322038, 0.2518088988460535, 0.40776107805949874, 0.33196621078815547, 0.5867391740767356, 0.6542854172940505, 0.49064950352627534, 0.5456631022326226, 0.45490970261466435, 0.42310674599295583, 0.7732235181128915, 0.3733966742705455, 0.6674749387255294, 0.7229572607685595, 0.5051831551921917, 0.3501078420761851, 0.269263325124163, 0.6074341383970799, 0.38680342384254485, 0.2843070466360036, 0.3124341616309452, 0.6830499099096764, 0.5606220769579866, 0.59421954938463, 0.580307858760063, 0.3591461618766185, 0.7066568169931434, 0.5427213653788738, 0.3972983916665697, 0.6454223206225669, 0.5535423226043389, 0.7656326104003235, 0.43346564725017395, 0.24707624461173144, 0.5176741861695549, 0.4476638551171744, 0.3250858454189476, 0.5358726125693919, 0.4967174856193487, 0.5108130471869893, 0.6992498852671155, 0.477741770723

In [21]:
samples = 10
volume = 150 
stock = [2,4]
number = len(stock)


size = (samples, number)
finvol = np.zeros(size)

stock_QAS = 2
stock_HBD = 4
DES_mole_fractions = Binary_DES_Generator(.2, .2, .8, .8, samples, 200)

count = 0
for row in DES_mole_fractions: 
    def f(x):
        for i in range(number):
            total = []
            place = stock[i]*x[i]
            total.append(place)
        total = sum(total)
        y = np.zeros(np.size(x))                                                                           
        y[0] = x[0] + x[1] - volume                                                                   
        for i in range(number-1):
            y[i+1] = (((stock[i])*x[i])/(total)) - row[i]
        return y
    x0 = np.array([100.0, 100.0, 100.0])  
    x = fsolve(f, x0)
    for i in range(number):
        finvol[count, i] = x[i]
    count = count + 1

print("finvol is", finvol)
number = len(finvol[0])
print(number)

 4000 feasible DES samples generated, clustered into 10 samples
finvol is [[73.60190978 76.39809022]
 [86.39044416 63.60955584]
 [59.16303714 90.83696286]
 [80.30776567 69.69223433]
 [65.03933234 84.96066766]
 [69.46016573 80.53983427]
 [89.56735151 60.43264849]
 [51.32643411 98.67356589]
 [83.40563463 66.59436537]
 [77.08195637 72.91804363]]
2


### Generalized

## Converting to Opentrons copyable

In [22]:
sepvol = []

for i in range(number):
    string = "comp" + str(i)
    string = []
    for row in finvol:
        hold = row[i]
        string.append(hold)
    sepvol.append(string)

sepvol.type()

AttributeError: 'list' object has no attribute 'type'

### Alternatively, you could use this next function if you already have a list you want to convert (as before when we saved the output of the des mole fractions)

In [11]:
def convert_mole_fractions_to_volumes_2(DES_mole_fractions, stock_QAS, stock_HBD):
    QAS = [] # empty list to append calculated volumes in microL
    HBD = []
    for row in DES_mole_fractions: 
        def f(x) :
            y = np.zeros(np.size(x))                                                                           
            y[0] = x[0] + x[1] - 150  #input desired volume                                                                   
            y[1] = ((stock_QAS*x[0])/((stock_QAS*x[0]) + (stock_HBD*x[1]))) - row[0]
            y[2] = ((stock_HBD*x[1])/((stock_QAS*x[0]) + (stock_HBD*x[1]))) - row[1]
            return y
        x0 = np.array([100.0, 100.0, 100.0])                                        
        x = fsolve(f, x0)
        QAS.append(x[0])
        HBD.append(x[1])
        volumes = [QAS,HBD]

    return(volumes)

In [12]:
convert_mole_fractions_to_volumes_2(A, 3, 2)

[[50.37813191068493,
  69.8743078602248,
  38.8337827761865,
  58.93897614454336,
  80.48455343512126,
  44.15645306941992,
  63.04142567854789,
  54.43997097718037,
  84.64882277069829,
  74.94087560275959,
  34.90974621258966,
  47.41323894896303,
  66.05067004968399,
  41.39644819398069,
  56.330013058789774,
  77.5871318135321,
  61.211996595146076,
  52.1597834935777,
  89.3508409827377,
  36.999788552109294,
  67.85769672228446,
  48.17121583667832,
  72.92446587921062,
  45.07251170141245,
  46.36132502314877,
  64.39463694552583,
  57.466482270832905,
  42.94560134923387,
  52.967361461769855,
  81.78623271753477,
  40.31645960367188,
  60.03094335339014,
  78.92870155469258,
  71.44919290222474,
  34.26440692694148,
  55.350452392555816,
  62.442061971394416,
  49.05377350402926,
  53.989395547798324,
  76.25958585567928,
  85.7899115297591,
  65.47074950213768,
  51.26830506720621,
  68.40707017600195,
  37.90070017935406,
  36.110559806212045,
  73.536271953554,
  70.6686371

### This code can be used to produce binary DES from the list of volumes and cocnentrated stock solutions of your components. Capable of switching between two different pipettes, but modify as necessary. Code is originally from Newcastle IGEM at Newcastle University, github can be found here https://github.com/jbird1223/Newcastle-iGEM

In [13]:
from opentrons import labware, instruments, robot
from sqlite3 import IntegrityError
robot.reset() #remove this when uplaoding code to robot

#####################################################################################################################################################
#####################################################################################################################################################		

# Import Labware

tiprack_300 = labware.load("opentrons-tiprack-300ul", '1')      
tiprack_1000 = labware.load("tiprack-1000ul", '4')                
Stock1 = labware.load("opentrons-tuberack-15ml", '2')                                           
wellplate_96 = labware.load("96-flat", '3')
trash = robot.fixed_trash

#####################################################################################################################################################
#####################################################################################################################################################

# Import Pipettes

P1000 = instruments.P1000_Single(
    mount = 'right',
    tip_racks = [tiprack_1000],
    trash_container = trash
)

P300 = instruments.P300_Single(
    mount='left',
    tip_racks=[tiprack_300],
    trash_container=trash 
)

#####################################################################################################################################################
#####################################################################################################################################################

#Insert DES Generator here. 

reagents1 = convert_mole_fractions_to_volumes(3, 4, 0.3, 0.2, 0.8, 0.7, 96, 192 )

reagent_pos1 = ['A1', 'A3']



#####################################################################################################################################################
#####################################################################################################################################################
# STOCK LABWARE 1

robot.home()                                                    # Homes robot and prevents any pipette bugs 
for counter, reagent in enumerate(reagents1,0):
                                                                # These objects are temporary and will only exist within this loop
    source      = reagent_pos1[counter]                         # Counter is use to index an independent list (e.g. reagent_pos)
    P1000list   = [source]                                      # This is then added to both list - used in testing 				
    P300listn   = [source]


    P300.pick_up_tip()                                          # Picks up pipette tip for both P10 and P300 to allow to alternate
    P1000.pick_up_tip()
    for well_counter, values in enumerate(reagent):             # Specifies the well position and the volume of reagent being 
        if values == float(0):                                  # If volume is 0, well is skipped  
            pass
        elif values < float(300):
            P300.distribute(                                     # If volume below 300, P300 used not p1000. Greater than 300 P1000 is used.
                values, 
                Stock1(source), 
                wellplate_96(well_counter).top(0.5),          # Prevents submerging tip in solution, not completely sterile, but beneficial
                blow_out=True,                                  # Removes excess from tip
                rate=1,                                         # How quick it aspirates/dispenses, lower (ie 0.5) if stock viscous
                new_tip='never')
            P300.touch_tip(wellplate_96(well_counter))         # Touches tip to remove any droplets
            P300.blow_out(wellplate_96(well_counter))
        else: 
            P1000.distribute(
                values, 
                Stock1(source), 
                wellplate_96(well_counter).top(0.5),
                blow_out=True,
                rate=1,
                new_tip='never')
            P1000.touch_tip(wellplate_96(well_counter))
            P1000.blow_out(wellplate_96(well_counter))
    P1000.drop_tip()
    P300.drop_tip()

for c in robot.commands(): # remove this when uploading code to robot
     print(c)


ModuleNotFoundError: No module named 'opentrons'